begin;

create table if not exists public.admins (
    user_id uuid primary key references auth.users (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.apartments (
    id bigint generated by default as identity primary key,
    name text not null,
    location text not null,
    city text,
    neighborhood text,
    price integer not null check (price >= 0),
    bedrooms integer not null check (bedrooms >= 0),
    bathrooms integer not null check (bathrooms >= 0),
    size integer not null check (size >= 0),
    image text not null,
    images text[] not null default '{}',
    description text default '',
    badge text default '',
    type text default 'Apartamento',
    rating numeric(2,1),
    reviews integer,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.rental_inquiries (
    id bigint generated by default as identity primary key,
    apartment_id bigint references public.apartments (id) on delete set null,
    apartment_name text not null,
    apartment_area text not null,
    full_name text not null,
    email text not null,
    phone text not null,
    dni text not null,
    birth_date date,
    nationality text not null,
    move_in_date date,
    rental_period text not null,
    occupation text not null,
    workplace text not null,
    monthly_income numeric,
    employment_type text not null,
    num_occupants integer,
    has_pets boolean not null default false,
    pets_details text,
    emergency_contact text not null,
    reference_notes text,
    additional_comments text,
    submitted_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_apartments_updated_at on public.apartments;
create trigger set_apartments_updated_at
before update on public.apartments
for each row execute function public.set_updated_at();

alter table public.admins enable row level security;
alter table public.apartments enable row level security;
alter table public.rental_inquiries enable row level security;

drop policy if exists "Admins can read own row" on public.admins;
create policy "Admins can read own row"
on public.admins
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Public can read apartments" on public.apartments;
create policy "Public can read apartments"
on public.apartments
for select
to public
using (true);

drop policy if exists "Admins can insert apartments" on public.apartments;
create policy "Admins can insert apartments"
on public.apartments
for insert
to authenticated
with check (exists (select 1 from public.admins where user_id = auth.uid()));

drop policy if exists "Admins can update apartments" on public.apartments;
create policy "Admins can update apartments"
on public.apartments
for update
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

drop policy if exists "Admins can delete apartments" on public.apartments;
create policy "Admins can delete apartments"
on public.apartments
for delete
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()));

drop policy if exists "Public can insert rental inquiries" on public.rental_inquiries;
create policy "Public can insert rental inquiries"
on public.rental_inquiries
for insert
to public
with check (true);

drop policy if exists "Admins can read rental inquiries" on public.rental_inquiries;
create policy "Admins can read rental inquiries"
on public.rental_inquiries
for select
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()));

insert into storage.buckets (id, name, public)
values ('apartment-images', 'apartment-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read apartment images" on storage.objects;
create policy "Public can read apartment images"
on storage.objects
for select
to public
using (bucket_id = 'apartment-images');

drop policy if exists "Admins can upload apartment images" on storage.objects;
create policy "Admins can upload apartment images"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
);

drop policy if exists "Admins can update apartment images" on storage.objects;
create policy "Admins can update apartment images"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
)
with check (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
);

drop policy if exists "Admins can delete apartment images" on storage.objects;
create policy "Admins can delete apartment images"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
);

insert into public.apartments (
    name, location, city, neighborhood, price, bedrooms, bathrooms, size, image, images, description, badge, type, rating, reviews
)
select *
from (
    values
    ('Apartamento Moderno en el Centro', 'Madrid, España', 'Madrid', 'Centro', 1200, 2, 2, 85, 'images/apartment1.jpg', array['images/apartment1.jpg','images/apartment1-1.jpg','images/apartment1-2.jpg']::text[], 'Apartamento moderno y luminoso, ideal para profesionales de la salud.', 'Destacado', 'Apartamento', 5.0, 24),
    ('Apartamento Espacioso con Vista', 'Barcelona, España', 'Barcelona', 'Eixample', 1500, 3, 2, 120, 'images/apartment2.jpg', array['images/apartment2.jpg','images/apartment2-1.jpg','images/apartment2-2.jpg']::text[], 'Espacioso apartamento con excelente ubicación y mucha luz natural.', 'Nuevo', 'Apartamento', 4.5, 18),
    ('Apartamento Céntrico y Acogedor', 'Valencia, España', 'Valencia', 'Ruzafa', 1000, 1, 1, 60, 'images/apartment3.jpg', array['images/apartment3.jpg','images/apartment3-1.jpg','images/apartment3-2.jpg']::text[], 'Perfecto para estancias cómodas con acceso rápido a zonas clave.', '', 'Apartamento', 4.0, 12),
    ('Loft Moderno en Malasaña', 'Madrid, España', 'Madrid', 'Malasaña', 1800, 2, 2, 95, 'images/apartment4.jpg', array['images/apartment4.jpg']::text[], 'Loft moderno con acabados premium y excelente conectividad.', '', 'Loft', 4.8, 32),
    ('Dúplex Acogedor', 'Sevilla, España', 'Sevilla', 'Triana', 900, 2, 1, 75, 'images/apartment5.jpg', array['images/apartment5.jpg']::text[], 'Dúplex funcional y acogedor, ideal para una estancia prolongada.', '', 'Dúplex', 4.3, 15),
    ('Penthouse con Vistas al Mar', 'Barcelona, España', 'Barcelona', 'Barceloneta', 2200, 3, 3, 150, 'images/apartment6.jpg', array['images/apartment6.jpg']::text[], 'Penthouse exclusivo con vistas al mar y grandes espacios.', '', 'Penthouse', 4.9, 45),
    ('Estudio Minimalista', 'Madrid, España', 'Madrid', 'Lavapiés', 750, 1, 1, 45, 'images/apartment7.jpg', array['images/apartment7.jpg']::text[], 'Estudio minimalista y práctico en zona céntrica.', '', 'Estudio', 4.2, 8),
    ('Casa con Jardín', 'Valencia, España', 'Valencia', 'Campanar', 2500, 4, 3, 200, 'images/apartment8.jpg', array['images/apartment8.jpg']::text[], 'Casa amplia con jardín privado y espacios familiares.', '', 'Casa', 4.7, 28),
    ('Apartamento Cerca del Hospital', 'Madrid, España', 'Madrid', 'Chamberí', 1100, 2, 1, 70, 'images/apartment9.jpg', array['images/apartment9.jpg']::text[], 'Ubicación estratégica para profesionales que trabajan en hospitales cercanos.', '', 'Apartamento', 4.6, 21),
    ('Apartamento Luminoso', 'Barcelona, España', 'Barcelona', 'Gràcia', 1350, 2, 1, 75, 'images/apartment10.jpg', array['images/apartment10.jpg']::text[], 'Apartamento luminoso con distribución funcional y ambiente tranquilo.', '', 'Apartamento', 4.4, 19)
) as seed(name, location, city, neighborhood, price, bedrooms, bathrooms, size, image, images, description, badge, type, rating, reviews)
where not exists (select 1 from public.apartments);

commit;
